# Generated by Django 6.0.6 on 2026-07-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(default='bags', max_length=50)),
                ('reorder_level', models.IntegerField(default=0)),
                ('status', models.CharField(default='Healthy', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('cell', models.CharField(max_length=10)),
                ('cell_leader', models.CharField(max_length=100)),
                ('meal_type', models.CharField(max_length=20)),
                ('meal_name', models.CharField(max_length=100)),
                ('menu_items', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=150)),
                ('invoice', models.CharField(max_length=50, unique=True)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('date', models.CharField(max_length=20)),
                ('purchaser', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=20)),
                ('meal_type', models.CharField(max_length=20)),
                ('person_given', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
            ],
        ),
    ]
