# Generated by Django 6.0.6 on 2026-07-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocknet_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('admin', 'admin'), ('procurement-officer', 'procurement-officer'), ('storekeeper', 'storekeeper'), ('stock-keeper', 'stock-keeper')], default='storekeeper', max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='item',
            name='unit',
            field=models.CharField(default='kg', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('name', 'category')},
        ),
    ]
